apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rotation-queue
  namespace: kube-system
  labels:
    k8s-app: rotation-queue
spec:
  selector:
    matchLabels:
      name: rotation-queue
  template:
    metadata:
      labels:
        name: rotation-queue
        k8s-app: rotation-queue
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
      - name: rotation-queue
        image: flex-repo.akam.ai/rotation-queue:latest
        env:
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 8080
          hostPort: 8123
          name: rotation-queue
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: rotation-queue
  name: rotation-queue
  namespace: kube-system
spec:
  selector:
    k8s-app: rotation-queue
  clusterIP: None
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: rotation-queue
  name: rotation-queue
  namespace: monitoring
spec:
  endpoints:
    - targetPort: 8080
      interval: 5s
      path: /metrics
      scheme: http
      honorLabels: true
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: rotation-queue

